name: Compile and Run Java

on:
  push:
    branches:
      - main

jobs:
  compile-and-run-java:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Compile Java
        run: javac HelloWorld.java  # Chỉ cần biên dịch ở đây

      - name: Run Java
        run: java HelloWorld  # Không cần biên dịch lại
